package findthedifference

// You are given two strings s and t.

// String t is generated by random shuffling string s and then add one more letter at a random position.

// Return the letter that was added to t.

func FindTheDifference(s string, t string) byte {
	// Initialize a map to count the occurrences of each character in string s
	counts := make(map[byte]int)

	for i := 0; i < len(s); i++ {
		counts[s[i]]++
	}

	for i := 0; i < len(t); i++ {
		if counts[t[i]] == 0 {
			return t[i]
		}
		counts[t[i]]--
	}

	return 0
}
